import React,{useEffect,useState} from 'react';
import {AlertTriangle,Bot,CheckCircle2,Eye,LoaderCircle,MessageCircle,Mic2,Pause,Play,Save,Send,ShieldCheck,Sparkles,Users} from 'lucide-react';
import {api} from '../api/client.js';

type Member={id:string;display_name:string;job_title:string;role:string;description:string;enabled:boolean;autonomy:'suggest'|'review'|'auto';avatar_style:string;accent_color:string;instructions:string};
type Settings={enabled:boolean;live_stream_url:string|null;live_chat_id:string|null;chat_source_mode:'channel'|'content';active_moderator_id:string;overlay_position:'top-left'|'top-right'|'bottom-left'|'bottom-right';overlay_scale:number;show_avatar:boolean;show_chat:boolean;anonymize_authors:boolean;voice_enabled:boolean;interaction_mode:'off'|'review'|'auto-safe';question_interval_seconds:number;response_cooldown_seconds:number;response_duration_seconds:number;max_turns_per_hour:number;max_chat_messages_per_turn:number;minimum_chat_messages:number;participation_prompt:string};
type Status={runtime:{running:boolean;busy:boolean;lastTickAt:string|null;lastError:string|null};session:{id:string;video_title:string;channel_title:string;status:string;chat_error:string|null}|null;turn:{id:string;kind:string;headline:string;text:string;cta:string|null}|null;recentTurns:Array<{id:string;kind:string;headline:string;text:string;status:string;created_at:string}>;chatConfigured:boolean;youtubeApiConfigured:boolean};

export function AiTeamPanel(){const [members,setMembers]=useState<Member[]>([]),[settings,setSettings]=useState<Settings|null>(null),[status,setStatus]=useState<Status|null>(null),[working,setWorking]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[testMessage,setTestMessage]=useState('Welche Quellen belegen die zentrale Aussage?');
async function load(){try{const [team,nextSettings,nextStatus]=await Promise.all([api<{members:Member[]}>('/api/ai-team'),api<Settings>('/api/ai-host/settings'),api<Status>('/api/ai-host/status')]);setMembers(team.members);setSettings(nextSettings);setStatus(nextStatus);setError('')}catch(e){setError(e instanceof Error?e.message:String(e))}}
useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),10_000);return()=>window.clearInterval(timer)},[]);
async function saveSettings(){if(!settings)return;setWorking('settings');setMessage('');try{await api('/api/ai-host/settings',{method:'PATCH',body:JSON.stringify({enabled:settings.enabled,liveStreamUrl:settings.live_stream_url||null,liveChatId:settings.live_chat_id||null,chatSourceMode:settings.chat_source_mode,activeModeratorId:settings.active_moderator_id,overlayPosition:settings.overlay_position,overlayScale:settings.overlay_scale,showAvatar:settings.show_avatar,showChat:settings.show_chat,anonymizeAuthors:settings.anonymize_authors,voiceEnabled:settings.voice_enabled,interactionMode:settings.interaction_mode,questionIntervalSeconds:settings.question_interval_seconds,responseCooldownSeconds:settings.response_cooldown_seconds,responseDurationSeconds:settings.response_duration_seconds,maxTurnsPerHour:settings.max_turns_per_hour,maxChatMessagesPerTurn:settings.max_chat_messages_per_turn,minimumChatMessages:settings.minimum_chat_messages,participationPrompt:settings.participation_prompt})});setMessage('Virtuelles Senderteam übernimmt die neuen Einstellungen.');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setWorking('')}}
async function updateMember(member:Member,patch:Partial<Member>){const optimistic={...member,...patch};setMembers(current=>current.map(item=>item.id===member.id?optimistic:item));try{await api(`/api/ai-team/members/${member.id}`,{method:'PATCH',body:JSON.stringify(patch)});await load()}catch(e){setError(e instanceof Error?e.message:String(e));await load()}}
async function sendTest(){setWorking('test');try{await api('/api/ai-host/test-chat',{method:'POST',body:JSON.stringify({message:testMessage,author:'Studiotest'})});setMessage('Testbeitrag wurde der Chat-Redaktion übergeben.');setTestMessage('');window.setTimeout(()=>void load(),2000)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setWorking('')}}
async function decide(id:string,action:'approve'|'reject'){await api(`/api/ai-host/turns/${id}/${action}`,{method:'POST'});await load()}
return <section className="ai-team-section">
  <header className="ai-team-title"><div><p className="eyebrow">Virtuelle TV-Firma</p><h2>Interaktives Senderteam</h2><p>Persistente KI-Mitarbeiter produzieren, moderieren und analysieren den Livechat direkt im OBS-Overlay.</p></div><span className={`integration-status ${settings?.enabled&&status?.runtime.running?'good':'warning'}`}><i/>{settings?.enabled?'Auf Sendung':'Pausiert'}</span></header>
  {message&&<div className="overview-notice"><CheckCircle2 size={16}/>{message}</div>}{error&&<div className="overview-notice error"><AlertTriangle size={16}/>{error}</div>}
  <div className="ai-team-live-grid"><article className="ai-team-program"><span className="ai-team-avatar"><i/></span><div><small>AKTUELLE KI-MODERATION</small><strong>{status?.turn?.headline??(status?.session?'Nächster Einsatz wird vorbereitet':'Wartet auf YouTube-Beitrag')}</strong><p>{status?.turn?.text??(status?.session?`${status.session.video_title} · ${status.session.channel_title}`:'Der Autopilot aktiviert Ava automatisch bei passenden Sendungen.')}</p></div><span className={status?.session?'state-pill success':'state-pill'}>{status?.session?.status??'bereit'}</span></article><article className="ai-team-safety"><ShieldCheck/><div><strong>Sicherer Autonomiemodus</strong><p>Chattexte sind Daten, keine Anweisungen. Namen, Kontaktdaten, Spam und Angriffe werden nicht verstärkt.</p></div></article></div>
  <div className="ai-staff-grid">{members.map(member=><article key={member.id} style={{'--staff-accent':member.accent_color} as React.CSSProperties} className={member.enabled?'enabled':''}><div className="staff-card-head"><span>{member.role==='moderator'?<Mic2/>:member.role==='producer'?<Play/>:member.role==='chat-analyst'?<MessageCircle/>:member.role==='fact-checker'?<ShieldCheck/>:<Sparkles/>}</span><label className="switch"><input type="checkbox" checked={member.enabled} onChange={event=>void updateMember(member,{enabled:event.target.checked})}/><i/></label></div><input className="staff-name-input" value={member.display_name} onChange={event=>setMembers(current=>current.map(item=>item.id===member.id?{...item,display_name:event.target.value}:item))} onBlur={()=>void updateMember(member,{display_name:member.display_name})}/><strong>{member.job_title}</strong><p>{member.description}</p><label>Autonomie<select value={member.autonomy} onChange={event=>void updateMember(member,{autonomy:event.target.value as Member['autonomy']})}><option value="auto">Automatisch</option><option value="review">Vor Freigabe prüfen</option><option value="suggest">Nur Vorschläge</option></select></label></article>)}</div>
  {settings&&<div className="ai-team-settings-grid"><section className="hub-panel"><header><div><p className="eyebrow">Overlay & Stimme</p><h3>Avatar-Regie</h3></div><Eye/></header><div className="friendly-settings-grid"><label><span>Position</span><select value={settings.overlay_position} onChange={e=>setSettings({...settings,overlay_position:e.target.value as Settings['overlay_position']})}><option value="top-left">Oben links</option><option value="top-right">Oben rechts</option><option value="bottom-left">Unten links</option><option value="bottom-right">Unten rechts</option></select></label><label><span>Größe</span><div className="range-field"><input type="range" min="65" max="140" value={settings.overlay_scale} onChange={e=>setSettings({...settings,overlay_scale:Number(e.target.value)})}/><strong>{settings.overlay_scale}%</strong></div></label><label><span>Frageintervall</span><div className="unit-input"><input type="number" min="20" max="900" value={settings.question_interval_seconds} onChange={e=>setSettings({...settings,question_interval_seconds:Number(e.target.value)})}/><em>Sek.</em></div></label><label><span>Einblenddauer</span><div className="unit-input"><input type="number" min="8" max="120" value={settings.response_duration_seconds} onChange={e=>setSettings({...settings,response_duration_seconds:Number(e.target.value)})}/><em>Sek.</em></div></label></div><div className="automation-toggles"><label><input type="checkbox" checked={settings.show_avatar} onChange={e=>setSettings({...settings,show_avatar:e.target.checked})}/><span><strong>Avatar zeigen</strong><small>Immer klar als KI-Moderation gekennzeichnet.</small></span></label><label><input type="checkbox" checked={settings.voice_enabled} onChange={e=>setSettings({...settings,voice_enabled:e.target.checked})}/><span><strong>Sprechen lassen</strong><small>TTS wird separat in OBS ausgegeben.</small></span></label></div></section>
  <section className="hub-panel"><header><div><p className="eyebrow">Livechat</p><h3>Interaktionsregie</h3></div><MessageCircle/></header><label>Chatquelle<select value={settings.chat_source_mode} onChange={e=>setSettings({...settings,chat_source_mode:e.target.value as Settings['chat_source_mode']})}><option value="channel">Eigener Sendekanal</option><option value="content">Chat des laufenden Quell-Livestreams</option></select></label>{settings.chat_source_mode==='channel'&&<label>URL des eigenen YouTube-Livestreams<input type="url" value={settings.live_stream_url??''} onChange={e=>setSettings({...settings,live_stream_url:e.target.value})} placeholder="https://www.youtube.com/watch?v=…"/></label>}<label>Reaktionsmodus<select value={settings.interaction_mode} onChange={e=>setSettings({...settings,interaction_mode:e.target.value as Settings['interaction_mode']})}><option value="auto-safe">Automatisch nach Sicherheitsfilter</option><option value="review">Redaktion gibt Antworten frei</option><option value="off">Keine Chatantworten</option></select></label><label>Teilnahmeaufruf<textarea rows={2} value={settings.participation_prompt} onChange={e=>setSettings({...settings,participation_prompt:e.target.value})}/></label><div className="chat-test-row"><input value={testMessage} onChange={e=>setTestMessage(e.target.value)} placeholder="Testbeitrag für den Chat"/><button onClick={()=>void sendTest()} disabled={!status?.session||!testMessage.trim()||working==='test'}>{working==='test'?<LoaderCircle className="spin"/>:<Send/>}Testen</button></div><small className={status?.chatConfigured?'good-text':'warning-text'}>{status?.chatConfigured?'YouTube-Chat ist abrufbereit.':status?.youtubeApiConfigured?'Chatquelle noch nicht aktiv.':'YouTube Data API-Key fehlt unter Medien-Einstellungen.'}</small></section></div>}
  <div className="ai-team-actions"><button className={settings?.enabled?'pause-button':'primary-button'} onClick={()=>settings&&setSettings({...settings,enabled:!settings.enabled})}>{settings?.enabled?<><Pause/>Team pausieren</>:<><Play/>Team aktivieren</>}</button><button className="primary-button" onClick={()=>void saveSettings()} disabled={!settings||Boolean(working)}>{working==='settings'?<LoaderCircle className="spin"/>:<Save/>}Teamkonfiguration speichern</button></div>
  {status?.recentTurns.some(turn=>turn.status==='pending')&&<section className="hub-panel moderation-review"><header><div><p className="eyebrow">Freigabemodus</p><h3>Wartende Moderationen</h3></div><Users/></header>{status.recentTurns.filter(turn=>turn.status==='pending').map(turn=><article key={turn.id}><div><strong>{turn.headline}</strong><p>{turn.text}</p></div><button onClick={()=>void decide(turn.id,'reject')}>Ablehnen</button><button className="primary-button" onClick={()=>void decide(turn.id,'approve')}>Freigeben</button></article>)}</section>}
 </section>}
