import Fastify from 'fastify';import helmet from '@fastify/helmet';import cors from '@fastify/cors';import rateLimit from '@fastify/rate-limit';import websocket from '@fastify/websocket';import multipart from '@fastify/multipart';import cookie from '@fastify/cookie';import dotenv from 'dotenv';import{z}from'zod';import{parseFeed,parseHtmlArticle}from'@ans/news-parser';import{summarize,makeScript}from'@ans/content-processing';import{assertPublicHttpUrl,redactLog,maskSecret}from'@ans/security';import{fetchHttpText}from'@ans/source-connectors';import{createSource,dashboardStats,getArticleDetail,getPublishedMainArticle,listArticles,listSources,recordSourceCheck,saveArticlePackage,saveAudioAsset,setArticleStatus,setSourceActive,updateSource}from'@ans/database';import{synthesizePiper}from'@ans/tts-engine';
dotenv.config();const app=Fastify({logger:true});await app.register(helmet,{contentSecurityPolicy:false});await app.register(cors,{origin:true,credentials:true});await app.register(rateLimit,{max:120,timeWindow:'1 minute'});await app.register(websocket);await app.register(multipart,{limits:{fileSize:50*1024*1024}});await app.register(cookie);
function isLocalTestFeed(raw:string){const url=new URL(raw);return ['127.0.0.1','localhost'].includes(url.hostname)&&url.port===String(process.env.APP_PORT??12000)&&url.pathname==='/test-feed.xml';}const allowPrivate=process.env.ALLOW_PRIVATE_SOURCES==='true';const stream={service:process.env.STREAM_SERVICE??'custom',server:process.env.STREAM_SERVER??'',streamKey:process.env.STREAM_KEY?maskSecret(process.env.STREAM_KEY):''};
const sourceSchema=z.object({name:z.string().min(1),url:z.string().url(),type:z.enum(['rss','atom','feed','website']).default('rss'),category:z.string().optional().nullable(),region:z.string().optional().nullable(),language:z.string().default('de'),description:z.string().optional().nullable(),priority:z.number().int().default(0),trustLevel:z.number().int().min(0).max(100).default(50),fetchIntervalSeconds:z.number().int().min(60).max(86400).default(900),maxArticles:z.number().int().min(1).max(100).default(20),maxFetchSeconds:z.number().int().min(1).max(60).default(20),active:z.boolean().default(true),userAgent:z.string().optional().nullable()});
function publicArticle(a:any){return a?{id:a.id,title:a.title,summary:a.summary??a.excerpt??'',source:a.source_name??'Quelle',status:a.status,updatedAt:a.fetched_at,audioPath:a.audio_path,durationSeconds:a.audio_duration_seconds}:null;}
app.get('/health',async()=>({status:'online',components:{backend:'online',database:process.env.DATABASE_URL?'configured':'not_configured',worker:'separate_process',obs:'disconnected',tts:process.env.PIPER_MODEL_PATH?'configured':'optional'},time:new Date().toISOString()}));
app.get('/test-feed.xml',async(_req,reply)=>reply.type('application/rss+xml').send(`<?xml version="1.0"?><rss version="2.0"><channel><title>Lokaler Testfeed</title><item><title>Testmeldung eins</title><link>http://127.0.0.1:${process.env.APP_PORT??12000}/test/articles/1</link><guid>local-1</guid><pubDate>Sun, 12 Jul 2026 10:00:00 GMT</pubDate><description>Reproduzierbarer lokaler Nachrichtentext für Integrations- und Regressionstests.</description></item></channel></rss>`));
app.get('/api/dashboard',async()=>{const c=await dashboardStats();const a=await listArticles(1);return{status:'Bereit',counts:{newArticles:c.new_articles,approved:c.approved,planned:c.planned,discarded:c.discarded,failedSources:c.failed_sources},current:{item:a[0]?.title??'Keine Nachricht geladen',next:'Keine Sendeliste geplant',scene:'Hauptnachrichten-Overlay'},actions:[]}});
app.get('/api/sources',async()=>listSources());app.post('/api/sources',async(req)=>{const body=sourceSchema.parse(req.body);await assertPublicHttpUrl(body.url,allowPrivate||isLocalTestFeed(body.url));return createSource(body);});app.put('/api/sources/:id',async(req)=>updateSource((req.params as any).id,sourceSchema.partial().parse(req.body)));app.post('/api/sources/:id/active',async(req)=>{const{active}=z.object({active:z.boolean()}).parse(req.body);return setSourceActive((req.params as any).id,active);});
app.post('/api/sources/test',async(req)=>{const body=z.object({url:z.string().url(),maxFetchSeconds:z.number().optional()}).parse(req.body);const res=await fetchHttpText(body.url,{timeoutMs:(body.maxFetchSeconds??10)*1000,maxBytes:512*1024,allowPrivate:allowPrivate||isLocalTestFeed(body.url),userAgent:process.env.NEWS_USER_AGENT});const detected=res.contentType.includes('xml')||/<(rss|feed)\b/i.test(res.body.slice(0,300))?'feed':'website';const preview=detected==='feed'?parseFeed(res.body,res.url).slice(0,5):[parseHtmlArticle(res.body,res.url)];await recordSourceCheck(null,'ok',{url:body.url,detected,status:res.status});return{detected,status:res.status,finalUrl:res.url,preview,etag:res.etag,lastModified:res.lastModified,paywallSuspected:/paywall|subscribe|abo/i.test(res.body),javascriptLikely:/__NEXT_DATA__|window\.__|app-root/i.test(res.body)}});
app.get('/api/articles',async(req)=>listArticles(Number((req.query as any).limit??100)));app.get('/api/articles/:id',async(req)=>getArticleDetail((req.params as any).id));
app.post('/api/articles/:id/process',async(req)=>{const a=await getArticleDetail((req.params as any).id);if(!a)throw new Error('Artikel nicht gefunden');const text=a.main_text??a.excerpt??a.title;const summary=summarize(text);const script=makeScript(a.title,summary,a.source_name??'der Quelle');await saveArticlePackage(a.id,summary,script,summary,`${a.title}: ${summary}`);return getArticleDetail(a.id);});
app.post('/api/articles/:id/status',async(req)=>{const{status}=z.object({status:z.enum(['new','review','approved','blocked','published','discarded'])}).parse(req.body);return setArticleStatus((req.params as any).id,status);});
app.post('/api/articles/:id/tts',async(req)=>{const a=await getArticleDetail((req.params as any).id);if(!a?.script_text)throw new Error('Kein Sprechertext vorhanden');if(!process.env.PIPER_MODEL_PATH)return{skipped:true,reason:'Piper ist nicht konfiguriert'};const out=await synthesizePiper(a.script_text,{modelPath:process.env.PIPER_MODEL_PATH,outputDirectory:process.env.TTS_OUTPUT_DIR??'generated/audio',piperExecutable:process.env.PIPER_EXECUTABLE});const duration=Math.max(1,Math.round(a.script_text.split(/\s+/).length/2.7));await saveAudioAsset(a.id,out.file,duration);return{file:out.file,durationSeconds:duration};});
app.get('/api/overlay/main',async()=>({article:publicArticle(await getPublishedMainArticle()),serverTime:new Date().toISOString()}));
app.get('/api/stream-profile',async()=>stream);app.get('/overlay/:name',async(_req,reply)=>reply.type('text/html').send(`<!doctype html><html><head><meta charset="utf-8"><title>Hauptnachrichten</title><style>body{margin:0;background:#07111f;color:#fff;font-family:system-ui,sans-serif}.wrap{padding:72px}.k{display:inline-block;background:#c1121f;padding:10px 16px;font-weight:800}.src{color:#b8c7d9}h1{font-size:72px;max-width:1500px}.summary{font-size:38px;max-width:1350px;line-height:1.3}</style></head><body><div class="wrap"><div class="k">LIVE</div><h1 id="t">Keine freigegebene Nachricht</h1><p class="summary" id="s"></p><p class="src" id="q"></p><p class="src" id="u"></p></div><script>async function load(){const r=await fetch('/api/overlay/main',{cache:'no-store'});const d=await r.json();const a=d.article;document.getElementById('t').textContent=a?.title||'Keine freigegebene Nachricht';document.getElementById('s').textContent=a?.summary||'';document.getElementById('q').textContent=a?'Quelle: '+a.source:'';document.getElementById('u').textContent=a?'Aktualisiert: '+new Date(a.updatedAt).toLocaleString():'';}load();setInterval(load,5000);</script></body></html>`));app.post('/api/actions/:name',async(req)=>{const name=(req.params as any).name;app.log.info(redactLog({event:'control_action',name}));return{accepted:true,name}});
app.listen({host:process.env.APP_HOST??'127.0.0.1',port:Number(process.env.APP_PORT??12000)});
