alter table sessions add column if not exists token_hash text;
create unique index if not exists idx_sessions_token_hash on sessions(token_hash) where token_hash is not null;
create table if not exists login_failures(id uuid primary key default gen_random_uuid(),email text,ip_address inet,reason text,created_at timestamptz default now());
alter table overlay_projects add column if not exists status text not null default 'draft';
alter table overlay_projects add column if not exists template text not null default 'main-news';
alter table overlay_versions add column if not exists status text not null default 'draft';
alter table overlay_versions add column if not exists created_by uuid references users(id);
alter table overlay_versions add column if not exists label text;
create unique index if not exists idx_overlay_one_published on overlay_versions(project_id) where status='published';
alter table media_assets add column if not exists storage_path text;
alter table media_assets add column if not exists sha256 text;
alter table media_assets add column if not exists attribution text;
alter table media_assets add column if not exists license_name text;
alter table media_assets add column if not exists metadata jsonb not null default '{}';
create table if not exists media_links(id uuid primary key default gen_random_uuid(),media_id uuid references media_assets(id) on delete cascade,article_id uuid references articles(id),overlay_project_id uuid references overlay_projects(id),purpose text not null default 'attachment',created_at timestamptz default now());
create index if not exists idx_media_links_media on media_links(media_id);
