import pg from 'pg';
import type {QueryResultRow} from 'pg';
export const pool=new pg.Pool({connectionString:process.env.DATABASE_URL});
export async function query<T extends QueryResultRow=QueryResultRow>(text:string,params?:unknown[]){return pool.query<T>(text,params)}
export async function closeDatabase(){await pool.end();}

export type EditorialStatus='new'|'review'|'approved'|'blocked'|'published'|'discarded';
export interface SourceRecord{ id:string; name:string; url:string; domain:string; type:string; category:string|null; region:string|null; language:string; description:string|null; priority:number; trust_level:number; fetch_interval_seconds:number; max_articles:number; max_fetch_seconds:number; active:boolean; etag:string|null; last_modified:string|null; last_success_at:string|null; last_error:string|null; consecutive_errors:number; created_at:string; updated_at?:string; }
export interface ArticleRecord{ id:string; source_id:string|null; source_name?:string; title:string; url:string; canonical_url:string|null; published_at:string|null; fetched_at:string; author:string|null; excerpt:string|null; main_text:string|null; content_hash:string; status:EditorialStatus; category:string|null; region:string|null; trust_score:number; warnings:string[]; }
export interface ArticleDetailRecord extends ArticleRecord{summary:string|null;script_text:string|null;screen_text:string|null;ticker_text:string|null;audio_path:string|null;audio_duration_seconds:number|null;}
export async function listSources(){return (await query<SourceRecord>('select * from sources where deleted_at is null order by created_at desc')).rows;}
export async function getSource(id:string){return (await query<SourceRecord>('select * from sources where id=$1 and deleted_at is null',[id])).rows[0]??null;}
export async function createSource(input:Record<string,unknown>){const url=new URL(String(input.url));return (await query<SourceRecord>(`insert into sources(name,url,domain,type,category,region,language,description,priority,trust_level,fetch_interval_seconds,max_articles,max_fetch_seconds,active,user_agent) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) returning *`,[input.name,input.url,url.hostname,input.type,input.category??null,input.region??null,input.language??'de',input.description??null,input.priority??0,input.trustLevel??50,input.fetchIntervalSeconds??900,input.maxArticles??20,input.maxFetchSeconds??20,input.active??true,input.userAgent??null])).rows[0];}
export async function updateSource(id:string,input:Record<string,unknown>){const current=await getSource(id);if(!current)throw new Error('Quelle nicht gefunden');const next:Record<string,unknown>={...current,...input};const url=new URL(String(next.url));return (await query<SourceRecord>(`update sources set name=$2,url=$3,domain=$4,type=$5,category=$6,region=$7,language=$8,description=$9,priority=$10,trust_level=$11,fetch_interval_seconds=$12,max_articles=$13,max_fetch_seconds=$14,active=$15,user_agent=$16,version=version+1 where id=$1 returning *`,[id,next.name,next.url,url.hostname,next.type,next.category,next.region,next.language,next.description,next.priority,next.trustLevel??next.trust_level,next.fetchIntervalSeconds??next.fetch_interval_seconds,next.maxArticles??next.max_articles,next.maxFetchSeconds??next.max_fetch_seconds,next.active,next.userAgent??null])).rows[0];}
export async function setSourceActive(id:string,active:boolean){return (await query<SourceRecord>('update sources set active=$2,version=version+1 where id=$1 and deleted_at is null returning *',[id,active])).rows[0];}
export async function dueSources(){return (await query<SourceRecord>(`select * from sources where active=true and deleted_at is null and (last_success_at is null or last_success_at + (fetch_interval_seconds || ' seconds')::interval <= now() or (last_error is not null and last_success_at is null)) order by priority desc, created_at asc`)).rows;}
export async function recordSourceCheck(sourceId:string|null,status:string,details:unknown){await query('insert into source_checks(source_id,status,details) values($1,$2,$3)',[sourceId,status,details]);}
export async function markSourceSuccess(id:string,etag?:string,lastModified?:string){await query('update sources set last_success_at=now(),last_error=null,consecutive_errors=0,etag=coalesce($2,etag),last_modified=coalesce($3,last_modified) where id=$1',[id,etag??null,lastModified??null]);}
export async function markSourceError(id:string,error:string){await query('update sources set last_error=$2,consecutive_errors=consecutive_errors+1 where id=$1',[id,error.slice(0,1000)]);}
export async function upsertArticle(input:{sourceId:string;title:string;url:string;canonicalUrl?:string;publishedAt?:string;author?:string;excerpt?:string;mainText?:string;contentHash:string;category?:string|null;region?:string|null;trustScore?:number;warnings?:string[]}){const canonical=input.canonicalUrl??input.url;return (await query<ArticleRecord>(`insert into articles(source_id,title,url,canonical_url,published_at,author,excerpt,main_text,content_hash,category,region,trust_score,warnings,status) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,'new') on conflict do nothing returning *`,[input.sourceId,input.title,input.url,canonical,input.publishedAt??null,input.author??null,input.excerpt??null,input.mainText??null,input.contentHash,input.category??null,input.region??null,input.trustScore??50,input.warnings??[]])).rows[0]??null;}
export async function listArticles(limit=100){return (await query<ArticleRecord>(`select a.*,s.name as source_name from articles a left join sources s on s.id=a.source_id where a.deleted_at is null order by coalesce(a.published_at,a.fetched_at) desc limit $1`,[limit])).rows;}
export async function getArticleDetail(id:string){return (await query<ArticleDetailRecord>(`select a.*,s.name as source_name,sm.summary,sc.text script_text,sc.screen_text,sc.ticker_text,ma.filename audio_path,aa.duration_seconds audio_duration_seconds from articles a left join sources s on s.id=a.source_id left join lateral (select * from summaries where article_id=a.id order by created_at desc limit 1) sm on true left join lateral (select * from scripts where article_id=a.id order by created_at desc limit 1) sc on true left join lateral (select aa.* from audio_assets aa join scripts sx on sx.id=aa.script_id where sx.article_id=a.id order by aa.id desc limit 1) aa on true left join media_assets ma on ma.id=aa.media_id where a.id=$1 and a.deleted_at is null`,[id])).rows[0]??null;}
export async function setArticleStatus(id:string,status:EditorialStatus){return (await query<ArticleRecord>(`update articles set status=$2,version=version+1 where id=$1 and deleted_at is null and $2=any('{new,review,approved,blocked,published,discarded}'::text[]) returning *`,[id,status])).rows[0];}
export async function saveArticlePackage(articleId:string,summary:string,script:string,screenText?:string,tickerText?:string){return query('with s as (insert into summaries(article_id,source_passages,summary,model_name,model_version,prompt_version) values($1,$2,$3,$4,$5,$6) returning id), sc as (insert into scripts(article_id,text,screen_text,ticker_text) values($1,$7,$8,$9) returning id) update articles set status=$10,version=version+1 where id=$1 returning *',[articleId,[],summary,'rule-based','1','article-to-broadcast-v1',script,screenText??summary,tickerText??summary.slice(0,140),'review']);}
export async function saveAudioAsset(articleId:string,filename:string,durationSeconds:number){return query(`with sc as (select id from scripts where article_id=$1 order by created_at desc limit 1), ma as (insert into media_assets(filename,mime_type,duration_seconds,usage) values($2,'audio/wav',$3,'article-voice') returning id) insert into audio_assets(script_id,media_id,duration_seconds) select sc.id,ma.id,$3 from sc,ma`,[articleId,filename,durationSeconds]);}
export async function getPublishedMainArticle(){return (await query<ArticleDetailRecord>(`select a.*,s.name source_name,sm.summary,sc.text script_text,ma.filename audio_path,aa.duration_seconds audio_duration_seconds from articles a left join sources s on s.id=a.source_id left join lateral (select * from summaries where article_id=a.id order by created_at desc limit 1) sm on true left join lateral (select * from scripts where article_id=a.id order by created_at desc limit 1) sc on true left join lateral (select aa.* from audio_assets aa join scripts sx on sx.id=aa.script_id where sx.article_id=a.id order by aa.id desc limit 1) aa on true left join media_assets ma on ma.id=aa.media_id where a.status in ('published','approved') and a.deleted_at is null order by case when a.status='published' then 0 else 1 end, coalesce(a.published_at,a.fetched_at) desc limit 1`)).rows[0]??null;}
export async function dashboardStats(){const r=await query(`select (select count(*)::int from articles where status='new' and deleted_at is null) new_articles,(select count(*)::int from articles where status in ('approved','published') and deleted_at is null) approved,(select count(*)::int from broadcast_items where status='planned') planned,(select count(*)::int from articles where status='discarded' and deleted_at is null) discarded,(select count(*)::int from sources where active=true and consecutive_errors>0 and deleted_at is null) failed_sources`);return r.rows[0];}
